version: "3.5"
services:
  mysql:
    image: mysql:8.3.0
    command: "--bind-address=0.0.0.0"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_TCP_PORT=${MYSQL_PORT}
      - MYSQL_BIND_ADDRESS=0.0.0.0
    volumes:
      - ./data/mysql:/var/lib/mysql # For persistent data storage
    ports:
      - 3308:3308
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: senitron-pos-backend/server:latest
    ports:
      - "8081:8081"
    environment:
      NODE_ENV: "${NODE_ENV}"
      PORT: "${PORT}"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
