/**
 * @file Automatically generated by @tsed/barrels.
 */
export * from "./EpcController.js";
export * from "./HelloWorldController.js";
export * from "./SellerController.js";
export * from "./ShopController.js";
